SELECT * from SH.CUSTOMERS;

DESC SH.CUSTOMERS;

SELECT CUST_FIRST_NAME||CUST_LAST_NAME ,CUST_YEAR_OF_BIRTH 
from sh.CUSTOMERS where CUST_YEAR_OF_BIRTH>1990;

SELECT * FROM SH.CUSTOMERS WHERE CUST_GENDER = 'M';

SELECT CUST_ID,CUST_FIRST_NAME||CUST_LAST_NAME,CUST_GENDER,CUST_CITY_ID,CUST_CITY
FROM SH.CUSTOMERS where CUST_GENDER = 'F' AND CUST_CITY = 'Sydney';

SELECT * FROM SH.CUSTOMERS WHERE CUST_INCOME_LEVEL = 'G: 130,000 - 149,999';

SELECT * FROM SH.CUSTOMERS WHERE CUST_CREDIT_LIMIT > 10000;

SELECT * FROM SH.CUSTOMERS WHERE CUST_STATE_PROVINCE = 'California';

SELECT * FROM SH.CUSTOMERS WHERE CUST_EMAIL IS NOT NULL;

SELECT * FROM SH.CUSTOMERS WHERE CUST_MARITAL_STATUS IS NULL;

SELECT * FROM SH.CUSTOMERS WHERE CUST_POSTAL_CODE LIKE '53%';

SELECT * FROM SH.CUSTOMERS WHERE CUST_CREDIT_LIMIT > 5000 AND CUST_YEAR_OF_BIRTH < 1980;

SELECT * from sh.CUSTOMERS where CUST_CITY in ('Almere','Amersfoort');

SELECT * from sh.CUSTOMERS where CUST_CREDIT_LIMIT is null;

SELECT * from sh.CUSTOMERS where  CUST_MAIN_PHONE_NUMBER like '487%';

SELECT * from sh.CUSTOMERS where CUST_MARITAL_STATUS ='married'  and CUST_INCOME_LEVEL LIKE '%Medium%';

SELECT * from sh.CUSTOMERS where CUST_LAST_NAME like 'G%';

SELECT * from sh.CUSTOMERS where CUST_CITY_ID = '51057';

SELECT * from sh.CUSTOMERS where CUST_VALID ='A';

--SELECT * from sh.CUSTOMERS where CUST_EFF_FROM > 2020;

--SELECT * from sh.CUSTOMERS where CUST_EFF_TO < 2021;

SELECT * from sh.CUSTOMERS where CUST_CREDIT_LIMIT BETWEEN 5000 and 9000;

SELECT * from sh.CUSTOMERS where CUST_CITY_ID = 101;

SELECT * from sh.CUSTOMERS where CUST_EMAIL like '@company.example.com';

SELECT * from sh.CUSTOMERS where CUST_TOTAL_ID = 52772;

SELECT * from sh.CUSTOMERS where CUST_SRC_ID in (10,20,30);

SELECT * from sh.CUSTOMERS where CUST_EMAIL IS NULL OR  CUST_CREDIT_LIMIT IS NULL;

SELECT CUST_CITY,COUNT(*) from sh.CUSTOMERS  group by  CUST_CITY;

SELECT CUST_CITY,count(*) from sh.CUSTOMERS group by CUST_CITY HAVING count(*)>100;

SELECT CUST_STATE_PROVINCE,COUNT(*) from sh.CUSTOMERS  group by  CUST_STATE_PROVINCE;

SELECT CUST_STATE_PROVINCE,count(*) from sh.CUSTOMERS group by CUST_STATE_PROVINCE HAVING count(*)< 50;

SELECT CUST_CITY,avg(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_CITY;

SELECT CUST_CITY,avg(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_CITY  HAVING avg(CUST_CREDIT_LIMIT)>8000;

SELECT CUST_MARITAL_STATUS,count(*) FROM sh.CUSTOMERS group by CUST_MARITAL_STATUS;

SELECT CUST_MARITAL_STATUS,count(*) FROM sh.CUSTOMERS group by CUST_MARITAL_STATUS HAVING  count(*)>200;

SELECT CUST_GENDER,avg(CUST_YEAR_OF_BIRTH) FROM sh.CUSTOMERS group by CUST_GENDER;

SELECT CUST_GENDER,avg(CUST_YEAR_OF_BIRTH) FROM sh.CUSTOMERS group by CUST_GENDER HAVING avg(CUST_YEAR_OF_BIRTH)>1990;

SELECT COUNTRY_ID,count(*) from sh.CUSTOMERS group by COUNTRY_ID;

SELECT COUNTRY_ID,count(*) from sh.CUSTOMERS group by COUNTRY_ID HAVING count(*)>1000;

SELECT CUST_STATE_PROVINCE,sum(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_STATE_PROVINCE;

SELECT CUST_STATE_PROVINCE,sum(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_STATE_PROVINCE HAVING sum(CUST_CREDIT_LIMIT)>10000;

SELECT CUST_INCOME_LEVEL,max(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_INCOME_LEVEL;

SELECT CUST_INCOME_LEVEL,max(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_INCOME_LEVEL HAVING max(CUST_CREDIT_LIMIT)>15000;

SELECT CUST_YEAR_OF_BIRTH,COUNT(*) from sh.CUSTOMERS group by CUST_YEAR_OF_BIRTH;

SELECT CUST_YEAR_OF_BIRTH,COUNT(*) from sh.CUSTOMERS group by CUST_YEAR_OF_BIRTH having COUNT(*)>50;

SELECT CUST_MARITAL_STATUS,avg(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_MARITAL_STATUS;

SELECT CUST_MARITAL_STATUS,avg(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_MARITAL_STATUS HAVING avg(CUST_CREDIT_LIMIT)<5000;

select CUST_EMAIL,count(*) from sh.CUSTOMERS group by CUST_EMAIL;

select CUST_EMAIL,count(*) from sh.CUSTOMERS group by CUST_EMAIL HAVING count(*)>500;

select CUST_VALID,avg(CUST_CREDIT_LIMIT) from sh.CUsSTOMERS group by CUST_VALID;

select CUST_VALID,avg(CUST_CREDIT_LIMIT) from sh.CUSTOMERS group by CUST_VALID HAVING avg(CUST_CREDIT_LIMIT)>7000;

select CUST_STATE_PROVINCE,CUST_CITY,count(*)from sh.CUSTOMERS group by CUST_STATE_PROVINCE,CUST_CITY having count(*)>50;  